// <auto-generated />
namespace Bank_PBD.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
<<<<<<<< HEAD:Bank_PBD/Migrations/202205251850187_Employee.Designer.cs
    public sealed partial class Employee : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Employee));
        
        string IMigrationMetadata.Id
        {
            get { return "202205251850187_Employee"; }
========
    public sealed partial class Messages : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Messages));
        
        string IMigrationMetadata.Id
        {
            get { return "202205251614230_Messages"; }
>>>>>>>> aeb5cb99da4fa5c25e6b64fb13b4e7f4fe1e3fc5:Bank_PBD/Migrations/202205251614230_Messages.Designer.cs
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
