// <auto-generated />
namespace Bank_PBD.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class Bank1 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Bank1));
        
        string IMigrationMetadata.Id
        {
            get { return "202205121610331_Bank1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
